package com.example.msalehstoreapp.util

const val PREFERENCE_NAME = "MY_APP_PREF"

const val PREF_LOGGED_IN = "PREF_LOGGED_IN"
const val PREF_NAME = "PREF_NAME"
const val PREF_CONTACT_EMAIL = "PREF_CONTACT_EMAIL"
const val PREF_USERNAME = "PREF_USERNAME"
const val PREF_ACCOUNTTYPE = "PREF_ACCOUNTTYPE"
const val PREF_SHARE_MESSAGE = "PREF_SHARE_MESSAGE"
const val PREF_MINIMUM_APP_VERSION = "PREF_MINIMUM_APP_VERSION"